theme: jekyll-theme-hacker
title: PHP Design Patterns
tagline: My Notes
description: >-
  My Notes on PHP Design Patterns.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - 01.MVC.md
  - 02.Singleton.md
  - 03.Dependency-Injection.md
  - 04.Factory.md
  - 05.Adapter.md
  - 07.Active-Record.md
  - 08.Observer.md
  - 09.Strategy.md
  - 10.Decorator.md
  - 11.Chain-of-Command.md
  - LICENSE.md