theme: jekyll-theme-hacker
title: PHP Design Patterns
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - 01.%20MVC/MVC.md
  - 02.%20Singleton/Singleton.md
  - 03.%20Dependency%20Injection/Dependency_Injection.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
