theme: jekyll-theme-hacker
title: PHP Design Patterns
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - 01.MVC.md
  - 02.Singleton.md
  - 03.Dependency_Injection.md
  - 04.Factory.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
